apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ol
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ol
            image: ajymau/bonuspayout
            envFrom:
            - secretRef:
                name: bp-database-secret
            imagePullPolicy: Always
            command:
            - /bin/sh
            - -c
            - python3 /scripts/batchframework.py
          restartPolicy: OnFailure

