apiVersion: batch/v1
kind: Job
metadata:
 name: batch
spec:
 backoffLimit: 0
 template:
   metadata:
     name: batch
   spec:
     volumes:
     - name: logs
       emptyDir: {}
     containers:
     - name: bonuspayout
       volumeMounts:
       - name: logs 
         mountPath: /logs
       image: ajymau/bonuspayout:dev-last
       envFrom:
       - secretRef:
           name: bp-database-secret
       imagePullPolicy: Always
       command:
       - /bin/sh
       - -c
       - /opt/ol/wlp/bin/server run
     - name: batchmgr
       volumeMounts:
       - name: logs
         mountPath: /tmp/logs
       image: ajymau/batchdriver:dev-last
       imagePullPolicy: Always
       command:
       - /bin/sh
       - -c
       - python3 /scripts/batchframework.py
     dnsPolicy: ClusterFirst
     restartPolicy: Never
     shareProcessNamespace: true
