#FROM openjdk:slim
FROM openliberty/open-liberty:21.0.0.5-full-java11-openj9-ubi
#FROM open-liberty:full-java11-openj9
USER root
RUN yum install -y lsof
RUN yum install -y iputils
RUN yum install -y curl
RUN mkdir -p /batchprops
COPY --chown=1001:0 ./batchprops /batchprops

#finally, install python for batch mgmt work
RUN yum update -y
# commenting out the next 3 items - used for debugging 
#RUN yum install -y wget
#RUN wget http://mirror.centos.org/centos/7/os/x86_64/Packages/telnet-0.17-65.el7_8.x86_64.rpm
#RUN yum install -y ./telnet-0.17-65.el7_8.x86_64.rpm

RUN yum install -y python3
RUN yum install -y procps

RUN mkdir -p /scripts
COPY --chown=1001:0 ./src/scripts /scripts

USER 1001
RUN python3
