#FROM openjdk:slim
FROM openliberty/open-liberty:21.0.0.5-full-java11-openj9-ubi
#FROM open-liberty:full-java11-openj9
USER root
RUN yum install -y lsof
RUN yum install -y iputils
RUN yum install -y curl
RUN mkdir -p /batchprops
COPY --chown=1001:0 ./batchprops /batchprops

#finally, install python for batch mgmt work
RUN yum update -y
RUN yum install -y python3
RUN yum install -y procps

RUN mkdir -p /scripts
COPY --chown=1001:0 ./src/scripts /scripts

USER 1001
RUN python3
