apiVersion: batch/v1
kind: Job
metadata:
 name: rebatch
spec:
 backoffLimit: 0
 template:
   metadata:
     name: batch
   spec:
     containers:
     - name: batch
       image: ajymau/bonuspayout:dev-last
       envFrom:
       - secretRef:
           name: bp-database-secret
       imagePullPolicy: Always
       command:
       - /bin/sh
       - -c
       - python3 /scripts/restartjob.py %JOB_ID%
     restartPolicy: Never

