FROM openliberty/open-liberty:kernel-slim-java11-openj9-ubi

# Add Liberty server configuration including all necessary features
COPY --chown=1001:0  server-OL-TLEx.xml /config/server.xml
COPY --chown=1001:0  postgresql.xml /config/postgresql.xml
COPY --chown=1001:0  postgresql-42.2.21.jar /opt/ol/wlp/usr/shared/resources/postgresql-42.2.21.jar

ENV VERBOSE=true
# This script will add the requested XML snippets to enable Liberty features and grow image to be fit-for-purpose using featureUtility. 
# Only available in 'kernel-slim'. The 'full' tag already includes all features for convenience.
RUN features.sh

# Add app
COPY --chown=1001:0  BonusPayout.war /config/dropins/

# This script will add the requested server configurations, apply any interim fixes and populate caches to optimize runtime
RUN configure.sh
